cv/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('addproject/', views.addproject, name='addproject'),
    path('saveproject/', views.saveproject, name='saveproject')
]

iisafriyanti/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('cv.urls', 'cv'), namespace='cv')),
]

cv/models.py
from django.db import models
from django.utils import timezone

# Create your models here.
class Project(models.Model):
	position = models.CharField(max_length=200)
	title = models.CharField(max_length=200)
	desc = models.TextField()
	created_date = models.DateTimeField(default=timezone.now)

class Person(models.Model):
	nama = models.CharField(max_length=200)

cv/forms.py
from django import forms

class Add_Project_Form(forms.Form):
    error_messages = {
        'required': 'Please type',
    }
    pos_attrs = {
        'type': 'text',
        'class': 'todo-form-input',
        'placeholder':'Your position'
    }
    title_attrs = {
        'type': 'text',
        'class': 'todo-form-input',
        'placeholder':'Title of the project'
    }
    description_attrs = {
        'type': 'text',
        'cols': 50,
        'rows': 4,
        'class': 'todo-form-textarea',
        'placeholder':'Description of the project'
    }

    position = forms.CharField(label='', required=True, max_length=27, widget=forms.TextInput(attrs=pos_attrs))
    title = forms.CharField(label='', required=True, max_length=27, widget=forms.TextInput(attrs=title_attrs))
    description = forms.CharField(label='', required=True, widget=forms.Textarea(attrs=description_attrs))

cv/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from .forms import Add_Project_Form
from .models import Project

response = {}

# Create your views here.
def index(request):
	project = Project.objects.all()
	response['project'] = project

	html = 'index.html'
	return render(request, html, response)

def addproject(request):
	response['title'] = 'Add Project'
	response['addproject_form'] = Add_Project_Form

	html = 'addproject.html'

	return render(request, html, response)

def saveproject(request):
	form = Add_Project_Form(request.POST or None)
	if(request.method == 'POST' and form.is_valid()):
		response['position'] = request.POST['position']
		response['title'] = request.POST['title']
		response['description'] = request.POST['description']
		project = Project(position=response['position'], title=response['title'],desc=response['description'])
		project.save()
		return HttpResponseRedirect('/')
	else:
		return HttpResponseRedirect('/')

cv/templates/addproject.html
{% extends "base.html" %}

{% block title %}
  Resume - Add Project
{% endblock %}

{% block content %}

<section class="resume-section p-3 p-lg-5 d-flex flex-column" id="projects">
	<div class="my-auto">
        <h2 class="mb-5">{{ title }}</h2>
        <div class="col-sm-12 form-row field-desc">
        	<form id="form" method="GET" action="{% url 'cv:saveproject' %}">
	        	{% csrf_token %}
	          {{ addproject_form.as_p }}
 
            <!-- <div class="form-group">
              <label for="id_position">Your Position</label>
              <input type="text" class="form-control" id="id_position"placeholder="Enter position" name="position" required>
            </div>
            <div class="form-group">
              <label for="id_title">Title of Project</label>
              <input type="text" class="form-control" id="id_title"placeholder="Enter title" name="title" required>
            </div>
            <div class="form-group">
              <label for="id_description">Description of Project</label>
              <textarea class="form-control" id="id_description" rows="3" name="description" required></textarea>
            </div> -->
	        	<input id="submit" type="submit" class="btn btn-lg btn-block btn-info" value="Submit">
       		</form>
        </div>
    </div>
</section>

{% endblock %}

cv/templates/base.html
{% load static %}

<html lang="en">

  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>{% block title %}{% endblock %}</title>

    <!-- Bootstrap core CSS -->
    <link rel="stylesheet" href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}">

    <!-- Custom fonts for this template -->
    <link href="https://fonts.googleapis.com/css?family=Saira+Extra+Condensed:100,200,300,400,500,600,700,800,900" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i,800,800i" rel="stylesheet">
    <link href="{% static 'vendor/font-awesome/css/font-awesome.min.css' %}  rel="stylesheet">
    <link href="{% static 'vendor/devicons/css/devicons.min.css' %}" rel="stylesheet">
    <link href="{% static 'vendor/simple-line-icons/css/simple-line-icons.css' %}" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="{% static 'css/resume.min.css' %}" rel="stylesheet">

  </head>

  <body id="page-top">
    <nav class="navbar navbar-expand-lg navbar-dark bg-primary fixed-top" id="sideNav">
      <a class="navbar-brand js-scroll-trigger" href="#page-top">
        <span class="d-block d-lg-none">Start Bootstrap</span>
        <span class="d-none d-lg-block">
          <img class="img-fluid img-profile rounded-circle mx-auto mb-2" src="{% static 'img/profile.jpg' %}" alt="">
        </span>
      </a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav">
          <li class="nav-item">
            <a class="nav-link js-scroll-trigger" href="#about">About</a>
          </li>
          <li class="nav-item">
            <a class="nav-link js-scroll-trigger" href="#portofolio">Portofolio</a>
          </li>
          <li class="nav-item">
            <a class="nav-link js-scroll-trigger" href="#projects">Projects</a>
          </li>
        </ul>
      </div>
    </nav>
    <div class="container-fluid p-0">
    {% block content %}

    {% endblock %}


    <!-- Bootstrap core JavaScript -->
    <script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
    <script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

    <!-- Plugin JavaScript -->
    <script src="{% static 'vendor/jquery-easing/jquery.easing.min.js' %}"></script>

    <!-- Custom scripts for this template -->
    <script src="{% static 'js/resume.min.js' %}"></script>

  </body>

</html>

cv/templates/footer.html
{% load static %}
    <!-- Bootstrap core JavaScript -->
    <script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
    <script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

    <!-- Plugin JavaScript -->
    <script src="{% static 'vendor/jquery-easing/jquery.easing.min.js' %}"></script>

    <!-- Custom scripts for this template -->
    <script src="{% static 'js/resume.min.js' %}"></script>

  </body>

</html>

cv/templates/header.html
{% load static %}

<html lang="en">

  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Resume - Iis Afriyanti</title>

    <!-- Bootstrap core CSS -->
    <link rel="stylesheet" href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}">

    <!-- Custom fonts for this template -->
    <link href="https://fonts.googleapis.com/css?family=Saira+Extra+Condensed:100,200,300,400,500,600,700,800,900" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i,800,800i" rel="stylesheet">
    <link href="{% static 'vendor/font-awesome/css/font-awesome.min.css' %}  rel="stylesheet">
    <link href="{% static 'vendor/devicons/css/devicons.min.css' %}" rel="stylesheet">
    <link href="{% static 'vendor/simple-line-icons/css/simple-line-icons.css' %}" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="{% static 'css/resume.min.css' %}" rel="stylesheet">

  </head>

cv/templates/index.html
{% extends "base.html" %}

{% block title %}
  Resume - Iis Afriyanti 
{% endblock %}
{% block content %}
    <section class="resume-section p-3 p-lg-5 d-flex d-column" id="about">
      <div class="my-auto">
          <h1 class="mb-0">Iis 
            <span class="text-primary">Afriyanti</span>
          </h1>
          <div class="subheading mb-5">R. 3212 A, Faculty of Computer Science, Universitas Indonesia, 16424, +62 21 786 3419 (ext 2502)
            <a href="mailto:iisafriyanti@cs.ui.ac.id">iisafriyanti@cs.ui.ac.id</a>
          </div>
          <p class="mb-5">I am a junior lecturer and research asssitant in Fasilkom UI. I love to learn new things related with linked data, open data, web, database, knowledge graph, and semantic web. </p>
          <ul class="list-inline list-social-icons mb-0">
            <li class="list-inline-item">
              <a href="https://twitter.com/iisafriyanti91">
                <span class="fa-stack fa-lg">
                  <i class="fa fa-circle fa-stack-2x"></i>
                  <i class="fa fa-twitter fa-stack-1x fa-inverse"></i>
                </span>
              </a>
            </li>
            <li class="list-inline-item">
              <a href="https://iisafriyanti.tumblr.com">
                <span class="fa-stack fa-lg">
                  <i class="fa fa-circle fa-stack-2x"></i>
                  <i class="fa fa-tumblr fa-stack-1x fa-inverse"></i>
                </span>
              </a>
            </li>
            <li class="list-inline-item">
              <a href="https://medium.com/@iisafriyanti91">
                <span class="fa-stack fa-lg">
                  <i class="fa fa-circle fa-stack-2x"></i>
                  <i class="fa fa-medium fa-stack-1x fa-inverse"></i>
                </span>
              </a>
            </li>
            <li class="list-inline-item">
              <a href="https://www.linkedin.com/in/iisafriyanti/">
                <span class="fa-stack fa-lg">
                  <i class="fa fa-circle fa-stack-2x"></i>
                  <i class="fa fa-linkedin fa-stack-1x fa-inverse"></i>
                </span>
              </a>
            </li>
            <li class="list-inline-item">
              <a href="https://github.com/iisafriyanti/">
                <span class="fa-stack fa-lg">
                  <i class="fa fa-circle fa-stack-2x"></i>
                  <i class="fa fa-github fa-stack-1x fa-inverse"></i>
                </span>
              </a>
            </li>
          </ul>
        </div>
      </section>

      <section class="resume-section p-3 p-lg-5 d-flex flex-column" id="portofolio">
        <div class="my-auto">
          <h2 class="mb-5">My Portofolio</h2>

          <div class="resume-item d-flex flex-column flex-md-row mb-5">
          <div class="resume-content mr-auto">
          I love to share my works on several repositories. You can look at my <a href="https://gitlab.com/iisafriyanti">Gitlab</a> and <a href="https://github.com/iisafriyanti"></a> to see the repositories. Or you may be interested in my portofolio related with research projects and publications on my <a href="https://www.researchgate.net/profile/Iis_Afriyanti2">Research Gate</a> and my other experiences on my <a href="https://www.linkedin.com/in/iisafriyanti/">LinkedIn</a>.
        </div>
        </div>

      </section>
      <section class="resume-section p-3 p-lg-5 d-flex flex-column" id="projects">
        <div class="my-auto">
          <h2 class="mb-5">On Going Projects</h2>
          
          

            {% if project %}
              {% for data in project %}
                <div class="resume-item d-flex flex-column flex-md-row mb-5">
                <div class="resume-content mr-auto">
                <h3 class="mb-0">{{ data.position }}</h3>
                <div class="subheading mb-3">{{ data.title }}</div>
                <p>{{ data.desc }}</p>
                </div>
                <div class="resume-date text-md-right">
                  <span class="text-primary">{{ data.created_date }}</span>
                </div>
                </div>
              {% endfor %}
            {% else %}
            <div class="resume-item d-flex flex-column flex-md-row mb-5">
            <div class="resume-content mr-auto">
              <h3 class="mb-0">Research Assistant</h3>
              <div class="subheading mb-3">Semantic Web for Knowledge Management of Higher Education in Indonesia</div>
              <p> Semantic Web-based system to accommodate the heterogeneity data of higher education.</p>
              </div>
            <div class="resume-date text-md-right">
              <span class="text-primary">January 2017 - Present</span>
            </div>
            </div>
            {% endif %}

          
          <a href="{% url 'cv:addproject' %}" class="btn btn-primary">Add Project</a>
        </div>

          <div class="subheading mb-3">Programming Languages &amp; Tools</div>
          <ul class="list-inline list-icons">
            <li class="list-inline-item">
              <i class="devicons devicons-html5"></i>
            </li>
            <li class="list-inline-item">
              <i class="devicons devicons-css3"></i>
            </li>
            <li class="list-inline-item">
              <i class="devicons devicons-javascript"></i>
            </li>
            <li class="list-inline-item">
              <i class="devicons devicons-jquery"></i>
            </li>
            <li class="list-inline-item">
              <i class="devicons devicons-codeigniter"></i>
            </li>
            <li class="list-inline-item">
              <i class="devicons devicons-bootstrap"></i>
            </li>
            <li class="list-inline-item">
              <i class="devicons devicons-wordpress"></i>
            </li>
            <li class="list-inline-item">
              <i class="devicons devicons-python"></i>
            </li>
            <li class="list-inline-item">
              <i class="devicons devicons-django"></i>
            </li>
            <li class="list-inline-item">
              <i class="devicons devicons-postgresql"></i>
            </li>
          </ul>
        </div>
      </section>
    
{% endblock %}

cv/templates/sidebar.html
  <body id="page-top">

    <nav class="navbar navbar-expand-lg navbar-dark bg-primary fixed-top" id="sideNav">
      <a class="navbar-brand js-scroll-trigger" href="#page-top">
        <span class="d-block d-lg-none">Start Bootstrap</span>
        <span class="d-none d-lg-block">
          <img class="img-fluid img-profile rounded-circle mx-auto mb-2" src="{% static 'img/profile.jpg' %}" alt="">
        </span>
      </a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav">
          <li class="nav-item">
            <a class="nav-link js-scroll-trigger" href="#about">About</a>
          </li>
          <li class="nav-item">
            <a class="nav-link js-scroll-trigger" href="#portofolio">Portofolio</a>
          </li> 
          <li class="nav-item">
            <a class="nav-link js-scroll-trigger" href="#projects">Projects</a> 
          </li>
        </ul>
      </div>
    </nav>